[Rainmeter]
Update=1000
AccurateText=1

[Variables]
FontColor=255,255,255,220
FontColor2=255,255,255,140
FontName=GeosansLight
FontName2=segoe wp semibold
FontSize=10

[BG]
Meter=Image
SolidColor=0,0,0,1
X=45
H=20
W=70
LeftMouseDownAction=!Execute ["taskmgr.exe"]

[BG2]
Meter=Image
SolidColor=0,0,0,1
X=0
H=18
W=45


; Network measures
[MeasureDownload]
Measure=NetIn
Interface="Wi-Fi"

[MeasureUpload]
Measure=NetOut
Interface="Wi-Fi"

; Lua script that keeps adding
[MeasureScript]
Measure=Script
ScriptFile=#@#DataUsage.lua

[MeterTitle]
Meter=STRING
X=0
Y=0
FontFace=#FontName2#
FontColor=#FontColor#
FontSize=#FontSize#
StringStyle=normal
StringAlign=Left
AntiAlias=1
Text="| Usage"

[MeterTotal]
Meter=String
MeasureName=MeasureScript
NumOfDecimals=2
Text="%1 MB"
X=50
Y=2
FontFace=GeosansLight
FontColor=#FontColor2#
FontSize=10
StringStyle=Bold
StringAlign=Left
AntiAlias=1
AutoScale=1
; Scale=100.00


